FROM node:16-buster-slim
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ./SlackAnalyticsFrontEnd/node/slackanalytics_front/package.json ./
COPY ./SlackAnalyticsFrontEnd/node/slackanalytics_front/package-lock.json* ./
COPY ./SlackAnalyticsFrontEnd/node/slackanalytics_front ./
RUN npm install --production --silent && mv node_modules ../
EXPOSE 3000
RUN chown -R node /usr/src/app
USER node
